# -*- coding: utf-8 -*-
"""Assignment Problem 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v4T2K4dE74AMe9Tt_tJCdA8Nqk5RBrZz

To-do list
1. Plot locations of hub in Gmap
2. Find distance from courier company to origin and then to destinations/ or origin to destinations only
3. Find shortest distance between origin and destinations when going through courier company.
4. Plot line ??

#Problem 1
"""

import pandas as pd
from geopy import Nominatim
from geopy.distance import great_circle
import gmplot


hubLocation = [["City-link Express", "Port Klang", 3.0319924887507144, 101.37344116244806],
               ["Pos Laju", "Petaling Jaya", 3.112924170027219, 101.63982650389863],
               ["GDEX", "Batu Caves", 3.265154613796736, 101.68024844550233],
               ["J&T", "Kajang", 2.9441205329488325, 101.7901521759029],
               ["DHL", "Sungai Buloh", 3.2127230893650065, 101.57467295692778]]

# creating df object with columns specified
df = pd.DataFrame(hubLocation, columns=['Courier Company', 'Delivery Hub', 'Latitude', 'Longitude'])
print(df)

# Question 1
# Get location : 

geolocator = Nominatim(user_agent="Assignment Problem 1")

courier_1 = geolocator.reverse("3.0319924887507144, 101.37344116244806")
print('\nCity-link Express (Port Klang)')
print(courier_1.address)

courier_2 = geolocator.reverse("3.112924170027219, 101.63982650389863")
print('\nPos Laju (Petaling Jaya)')
print(courier_2.address)

courier_3 = geolocator.reverse("3.265154613796736, 101.68024844550233")
print('\nGDEX (Batu Caves)')
print(courier_3.address)

courier_4 = geolocator.reverse("2.9441205329488325, 101.7901521759029")
print('\nJ&T (Kajang)')
print(courier_4.address)

courier_5 = geolocator.reverse("3.2127230893650065, 101.57467295692778")
print('\nDHL (Sungai Buloh)')
print(courier_5.address)

"""#Plot the hub location using gmplot

"""

apikey = 'AIzaSyAVVnomYZhH6Z8zvfckBg3l_iHuujD1aqc'  # (your API key here)
gmap = gmplot.GoogleMapPlotter(3.112924170027219, 101.63982650389863, 11, apikey=apikey)

gmap.marker(3.0319924887507144, 101.37344116244806)
gmap.marker(3.112924170027219, 101.63982650389863)
gmap.marker(3.265154613796736, 101.68024844550233)
gmap.marker(2.9441205329488325, 101.7901521759029)
gmap.marker(3.2127230893650065, 101.57467295692778)

gmap.draw('map.html')

"""# Question 2"""

lst = [['Rawang', 3.3615395462207878, 101.56318183511695, 'Bukit Jelutong', 3.1000170516638885, 101.53071480907951],
       ['Subang Jaya', 3.049398375759954, 101.58546611160301, 'Puncak Alam', 3.227994355250716, 101.42730357605375],
       ['Ampang', 3.141855957281073, 101.76158583424586, 'Cyberjaya', 2.9188704151716256, 101.65251821655471]]

ori_1 = (3.3615395462207878, 101.56318183511695)
des_1 = (3.1000170516638885, 101.53071480907951)
print(great_circle(ori_1, des_1).km)

ori_1 = (3.049398375759954, 101.58546611160301)
des_1 = (3.227994355250716, 101.42730357605375)
print(great_circle(ori_1, des_1).km)

ori_1 = (3.141855957281073, 101.76158583424586)
des_1 = (2.9188704151716256, 101.65251821655471)
print(great_circle(ori_1, des_1).km)
